// src/lib/components/PresetChips.svelte
<script lang="ts">
  import Icon from './Icon.svelte';
  import type { FluentIconName } from '../icons';
  import { store } from '../stores/tweaks.svelte';
  const presets = [
    { key: 'minimal',     label: 'Minimal',     icon: 'Sparkles' satisfies FluentIconName,  hint: 'Show file extensions, disable telemetry & Bing.' },
    { key: 'recommended', label: 'Recommended', icon: 'ShieldOff' satisfies FluentIconName, hint: 'Balanced privacy + a clean UI.' },
    { key: 'aggressive',  label: 'Aggressive',  icon: 'Flame' satisfies FluentIconName,     hint: 'Strip Xbox, location, optional features.' }
  ] as const;
</script>

<div class="chips">
  <span class="lbl">Presets:</span>
  {#each presets as p}
    <button
      class="chip"
      class:active={store.preset === p.key}
      title={p.hint}
      onclick={() => store.applyPreset(store.preset === p.key ? null : p.key)}
    >
      <Icon name={p.icon} size={13} bold={store.preset === p.key} />
      {p.label}
    </button>
  {/each}
  {#if store.preset}
    <button class="chip clear" onclick={() => store.applyPreset(null)}>Clear</button>
  {/if}
</div>

<style>
  .chips {
    display: flex;
    align-items: center;
    gap: 8px;
    flex-wrap: wrap;
  }
  .lbl { font-size: 12px; color: var(--text-tertiary); margin-right: 2px; }
  .chip {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    padding: 5px 12px;
    border-radius: 999px;
    font-size: 12px;
    font-weight: 500;
    color: var(--text-secondary);
    background: var(--surface-card);
    border: 1px solid var(--stroke-subtle);
    transition: all var(--motion-fast) var(--ease-decel);
  }
  .chip:hover { background: var(--surface-card-hover); color: var(--text-primary); }
  .chip.active {
    background: rgba(76,194,255,0.14);
    border-color: rgba(76,194,255,0.40);
    color: var(--accent-text);
  }
  .chip.clear { color: var(--text-tertiary); }
</style>

// src/lib/components/PresetChips.tsx
import './PresetChips.css';
import { Icon } from './Icon';
import { useTweaks } from '../stores/tweaks';
import type { FluentIconName } from '../icons';
import type { Preset } from '../stores/tweaks';

const presets: { key: Exclude<Preset, null>; label: string; icon: FluentIconName; hint: string }[] = [
  { key: 'minimal',     label: 'Minimal',     icon: 'Sparkles',  hint: 'Show file extensions, disable telemetry & Bing.' },
  { key: 'recommended', label: 'Recommended', icon: 'ShieldOff', hint: 'Balanced privacy + a clean UI.' },
  { key: 'aggressive',  label: 'Aggressive',  icon: 'Flame',     hint: 'Strip Xbox, location, optional features.' }
];

export function PresetChips() {
  const preset = useTweaks((s) => s.preset);
  const applyPreset = useTweaks((s) => s.applyPreset);

  return (
    <div className="chips">
      <span className="lbl">Presets:</span>
      {presets.map((p) => (
        <button
          key={p.key}
          type="button"
          className={`chip${preset === p.key ? ' active' : ''}`}
          title={p.hint}
          onClick={() => applyPreset(preset === p.key ? null : p.key)}
        >
          <Icon name={p.icon} size={13} bold={preset === p.key} />
          {p.label}
        </button>
      ))}
      {preset && (
        <button type="button" className="chip clear" onClick={() => applyPreset(null)}>Clear</button>
      )}
    </div>
  );
}
