// src/lib/components/ProfilesPanel.svelte
<script lang="ts">
  import { invoke } from '@tauri-apps/api/core';
  import { onMount } from 'svelte';
  import Icon from './Icon.svelte';
  import { store } from '../stores/tweaks.svelte';
  import type { Profile } from '../types';

  let profiles = $state<Profile[]>([]);
  let loading = $state(false);

  async function load() {
    loading = true;
    try {
      profiles = await invoke<Profile[]>('list_profiles');
    } catch (e) {
      store.toast({ kind: 'err', msg: `Profiles: ${e}` });
    } finally {
      loading = false;
    }
  }

  function summarise(p: Profile) {
    let applied = 0;
    let notApplied = 0;
    for (const id of p.tweak_ids) {
      if (store.stateOf(id) === 'applied') applied++;
      else notApplied++;
    }
    return { total: p.tweak_ids.length, applied, notApplied };
  }

  function selectProfile(p: Profile) {
    store.selectProfile(p.tweak_ids);
    store.toast({
      kind: 'info',
      msg: `${p.name}: ${store.selected.size} tweak${store.selected.size === 1 ? '' : 's'} selected. Hit Apply to commit.`
    });
  }

  async function applyProfile(p: Profile) {
    const stats = summarise(p);
    if (stats.notApplied === 0) {
      store.toast({ kind: 'info', msg: `${p.name}: already fully applied.` });
      return;
    }
    store.confirm({
      title: `Apply "${p.name}"?`,
      body: `${p.description}\n\nWill apply ${stats.notApplied} tweak${stats.notApplied === 1 ? '' : 's'} (${stats.applied} already applied).`,
      confirmLabel: `Apply ${stats.notApplied}`,
      onconfirm: async () => {
        store.selectProfile(p.tweak_ids);
        await store.applySelection(stats.notApplied >= 5);
      }
    });
  }

  onMount(load);
</script>

<div class="profiles">
  <p class="lede">
    Curated bundles. Click a profile to select every tweak in it; Apply runs them all.
    The progress ring shows how much of the profile is already in place — including changes you made outside this app.
  </p>

  {#if loading && profiles.length === 0}
    <p class="status">Loading…</p>
  {:else}
    <div class="grid">
      {#each profiles as p (p.id)}
        {@const s = summarise(p)}
        {@const pct = s.total === 0 ? 0 : Math.round((s.applied / s.total) * 100)}
        <article class="card">
          <header>
            <div class="icon-wrap"><Icon name={p.icon as any} size={20} /></div>
            <div class="title">
              <h3>{p.name}</h3>
              <p class="count">{s.applied}/{s.total} applied</p>
            </div>
            <div
              class="ring"
              style="--pct: {pct}%"
              title="{pct}% of this profile is currently applied"
            >
              {pct}%
            </div>
          </header>
          <p class="desc">{p.description}</p>
          <div class="actions">
            <button class="ghost" onclick={() => selectProfile(p)}>
              Select tweaks
            </button>
            <button class="primary" onclick={() => applyProfile(p)} disabled={s.notApplied === 0}>
              {s.notApplied === 0 ? 'Fully applied' : `Apply ${s.notApplied}`}
            </button>
          </div>
        </article>
      {/each}
    </div>
  {/if}
</div>

<style>
  .profiles {
    display: flex;
    flex-direction: column;
    gap: 14px;
  }
  .lede {
    margin: 0 0 4px;
    color: var(--text-secondary);
    font-size: 13px;
    line-height: 1.5;
    max-width: 80ch;
  }
  .status { color: var(--text-tertiary); }
  .grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
    gap: 14px;
  }
  .card {
    display: flex;
    flex-direction: column;
    gap: 10px;
    padding: 16px;
    background: var(--surface-card);
    border: 1px solid var(--stroke-subtle);
    border-radius: var(--radius-md);
    transition: all var(--motion-fast) var(--ease-decel);
  }
  .card:hover {
    background: var(--surface-card-hover);
    border-color: var(--stroke-default);
    box-shadow: var(--shadow-card);
  }
  header {
    display: grid;
    grid-template-columns: auto 1fr auto;
    gap: 12px;
    align-items: center;
  }
  .icon-wrap {
    width: 36px; height: 36px;
    display: grid;
    place-items: center;
    border-radius: var(--radius-sm);
    background: var(--accent-overlay-weak);
    color: var(--accent-fill);
  }
  .title h3 {
    margin: 0;
    font-size: 15px;
    font-weight: 600;
    color: var(--text-primary);
  }
  .count {
    margin: 2px 0 0;
    font-size: 11px;
    color: var(--text-tertiary);
    font-variant-numeric: tabular-nums;
  }
  .ring {
    width: 44px; height: 44px;
    border-radius: 50%;
    background:
      conic-gradient(var(--accent-fill) var(--pct), var(--stroke-subtle) var(--pct));
    display: grid;
    place-items: center;
    font-size: 10.5px;
    font-weight: 600;
    color: var(--text-primary);
    position: relative;
  }
  .ring::before {
    content: "";
    position: absolute;
    inset: 4px;
    border-radius: 50%;
    background: var(--surface-card);
  }
  .ring { isolation: isolate; }
  .ring::before { z-index: -1; }
  .desc {
    margin: 0;
    color: var(--text-secondary);
    font-size: 12.5px;
    line-height: 1.5;
  }
  .actions {
    display: flex;
    gap: 8px;
    margin-top: 4px;
  }
  .actions button {
    flex: 1;
    padding: 6px 12px;
    font-size: 12.5px;
    font-weight: 500;
    border-radius: var(--radius-sm);
    cursor: pointer;
    transition: all var(--motion-fast) var(--ease-decel);
  }
  .ghost {
    background: transparent;
    border: 1px solid var(--stroke-default);
    color: var(--text-primary);
  }
  .ghost:hover { background: var(--surface-card-hover); }
  .primary {
    background: var(--accent-fill);
    border: 1px solid var(--accent-fill);
    color: var(--text-on-accent);
  }
  .primary:hover:not(:disabled) { filter: brightness(1.08); }
  .primary:disabled {
    background: var(--surface-card-active);
    border-color: var(--stroke-subtle);
    color: var(--text-tertiary);
    cursor: not-allowed;
  }
</style>

// src/lib/components/ProfilesPanel.tsx
import { useEffect, useState, type CSSProperties } from 'react';
import { invoke } from '@tauri-apps/api/core';
import {
  Card,
  Button,
  Title3,
  Body1,
  Caption1,
  Spinner,
  Text,
  makeStyles,
  shorthands,
  tokens
} from '@fluentui/react-components';
import { Icon } from './Icon';
import { useTweaks } from '../stores/tweaks';
import type { FluentIconName } from '../icons';
import type { Profile } from '../../types';

const useStyles = makeStyles({
  lede: { display: 'block', maxWidth: '70ch', marginBottom: tokens.spacingVerticalL, color: tokens.colorNeutralForeground2 },
  status: {
    display: 'flex',
    alignItems: 'center',
    columnGap: tokens.spacingHorizontalS,
    color: tokens.colorNeutralForeground3,
    ...shorthands.padding(tokens.spacingVerticalXL, 0)
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
    gap: tokens.spacingHorizontalL
  },
  card: {
    display: 'flex',
    flexDirection: 'column',
    rowGap: tokens.spacingVerticalM,
    ...shorthands.padding(tokens.spacingVerticalL, tokens.spacingHorizontalL),
    backgroundColor: tokens.colorNeutralBackground2
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    columnGap: tokens.spacingHorizontalM
  },
  iconWrap: {
    width: '44px',
    height: '44px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorBrandBackground2,
    color: tokens.colorBrandForeground1,
    flexShrink: 0
  },
  titleCol: { flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', rowGap: '2px' },
  title: { margin: 0 },
  ring: {
    width: '52px',
    height: '52px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorNeutralForeground1,
    background: `conic-gradient(${tokens.colorBrandForeground1} var(--pct, 0%), ${tokens.colorNeutralStroke2} 0)`,
    position: 'relative',
    flexShrink: 0,
    ':before': {
      content: '""',
      position: 'absolute',
      inset: '4px',
      borderRadius: '50%',
      backgroundColor: tokens.colorNeutralBackground2
    },
    '& > span': { position: 'relative', zIndex: 1 }
  },
  desc: { color: tokens.colorNeutralForeground2 },
  actions: {
    display: 'flex',
    columnGap: tokens.spacingHorizontalS,
    marginTop: 'auto'
  }
});

export function ProfilesPanel() {
  const s = useStyles();
  const stateOf = useTweaks((s) => s.stateOf);
  const selected = useTweaks((s) => s.selected);
  const selectProfile = useTweaks((s) => s.selectProfile);
  const applySelection = useTweaks((s) => s.applySelection);
  const confirm = useTweaks((s) => s.confirm);
  const toast = useTweaks((s) => s.toast);

  const [profiles, setProfiles] = useState<Profile[]>([]);
  const [loading, setLoading] = useState(false);

  async function load() {
    setLoading(true);
    try {
      const next = await invoke<Profile[]>('list_profiles');
      setProfiles(next);
    } catch (e) {
      toast({ kind: 'err', msg: `Profiles: ${e}` });
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    void load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function summarise(p: Profile) {
    let applied = 0;
    let notApplied = 0;
    for (const id of p.tweak_ids) {
      if (stateOf(id) === 'applied') applied++;
      else notApplied++;
    }
    return { total: p.tweak_ids.length, applied, notApplied };
  }

  function handleSelect(p: Profile) {
    selectProfile(p.tweak_ids);
    const size = useTweaks.getState().selected.size;
    toast({
      kind: 'info',
      msg: `${p.name}: ${size} tweak${size === 1 ? '' : 's'} selected. Hit Apply to commit.`
    });
  }

  function handleApply(p: Profile) {
    const stats = summarise(p);
    if (stats.notApplied === 0) {
      toast({ kind: 'info', msg: `${p.name}: already fully applied.` });
      return;
    }
    confirm({
      title: `Apply "${p.name}"?`,
      body: `${p.description}\n\nWill apply ${stats.notApplied} tweak${stats.notApplied === 1 ? '' : 's'} (${stats.applied} already applied).`,
      confirmLabel: `Apply ${stats.notApplied}`,
      onconfirm: async () => {
        selectProfile(p.tweak_ids);
        await applySelection(stats.notApplied >= 5);
      }
    });
  }

  void selected;

  return (
    <div>
      <Body1 className={s.lede}>
        Curated bundles. Click a profile to select every tweak in it; Apply runs them all.
        The progress ring shows how much of the profile is already in place — including changes you made outside this app.
      </Body1>

      {loading && profiles.length === 0 ? (
        <div className={s.status}><Spinner size="tiny" /> <Text>Loading…</Text></div>
      ) : (
        <div className={s.grid}>
          {profiles.map((p) => {
            const stats = summarise(p);
            const pct = stats.total === 0 ? 0 : Math.round((stats.applied / stats.total) * 100);
            const ringStyle = { '--pct': `${pct}%` } as CSSProperties;
            return (
              <Card key={p.id} className={s.card} appearance="filled-alternative">
                <div className={s.header}>
                  <div className={s.iconWrap}>
                    <Icon name={p.icon as FluentIconName} size={20} />
                  </div>
                  <div className={s.titleCol}>
                    <Title3 as="h3" className={s.title}>{p.name}</Title3>
                    <Caption1>{stats.applied}/{stats.total} applied</Caption1>
                  </div>
                  <div
                    className={s.ring}
                    style={ringStyle}
                    title={`${pct}% of this profile is currently applied`}
                  >
                    <span>{pct}%</span>
                  </div>
                </div>
                <Body1 className={s.desc}>{p.description}</Body1>
                <div className={s.actions}>
                  <Button appearance="secondary" onClick={() => handleSelect(p)}>
                    Select tweaks
                  </Button>
                  <Button
                    appearance="primary"
                    onClick={() => handleApply(p)}
                    disabled={stats.notApplied === 0}
                  >
                    {stats.notApplied === 0 ? 'Fully applied' : `Apply ${stats.notApplied}`}
                  </Button>
                </div>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}
