// src/lib/components/TweakCard.svelte
<script lang="ts">
  import Icon from './Icon.svelte';
  import type { DetectionState, Tweak, TweakStatus } from '../types';
  import SeverityBadge from './SeverityBadge.svelte';
  import Toggle from './Toggle.svelte';

  let {
    tweak,
    applied,
    selected,
    status,
    onToggleApply,
    onToggleSelected
  }: {
    tweak: Tweak;
    applied: boolean;
    selected: boolean;
    status?: TweakStatus | null;
    onToggleApply: () => void;
    onToggleSelected: () => void;
  } = $props();

  let state: DetectionState = $derived(status?.state ?? (applied ? 'applied' : 'not_applied'));

  let opCount = $derived(
    tweak.registry.length + tweak.services.length + tweak.appx.length + (tweak.ps_apply ? 1 : 0)
  );
</script>

<article class="card" class:applied class:selected class:modified={state === 'modified'} class:risky={tweak.severity === 'risky'}>
  <button
    type="button"
    class="select"
    role="checkbox"
    aria-checked={selected}
    aria-label={selected ? `Deselect ${tweak.name}` : `Select ${tweak.name}`}
    onclick={(e) => { e.stopPropagation(); onToggleSelected(); }}
  >
    {#if selected}<Icon name="Check" size={12} strokeWidth={3} />{/if}
  </button>

  <div class="body">
    <header>
      <h3>{tweak.name}</h3>
      <SeverityBadge level={tweak.severity} />
    </header>

    <p class="desc">{tweak.description}</p>

    {#if tweak.warning}
      <div class="warn">
        <Icon name="AlertTriangle" size={13} strokeWidth={2} />
        <span>{tweak.warning}</span>
      </div>
    {/if}

    <footer>
      <span class="ops" title="{opCount} operation{opCount === 1 ? '' : 's'}">
        {opCount} op{opCount === 1 ? '' : 's'}
      </span>
      {#if tweak.presets.length > 0}
        <span class="dot-sep">·</span>
        {#each tweak.presets as p}
          <span class="preset">{p}</span>
        {/each}
      {/if}
      {#if state === 'applied'}
        <span class="dot-sep">·</span>
        <span class="applied-tag"><Icon name="Check" size={10} strokeWidth={3} /> Applied</span>
      {:else if state === 'modified'}
        <span class="dot-sep">·</span>
        <span class="modified-tag" title="{status?.ops_matching ?? 0} of {status?.ops_total ?? 0} settings match the desired state. Another tool may have changed some of these.">
          <Icon name="AlertTriangle" size={10} strokeWidth={2.5} />
          Modified externally ({status?.ops_matching}/{status?.ops_total})
        </span>
      {/if}
    </footer>
  </div>

  <div class="action">
    <Toggle checked={applied} onchange={onToggleApply} />
  </div>
</article>

<style>
  .card {
    display: grid;
    grid-template-columns: 18px 1fr auto;
    gap: 14px;
    align-items: flex-start;
    padding: 14px 16px;
    background: var(--surface-card);
    border: 1px solid var(--stroke-subtle);
    border-radius: var(--radius-md);
    transition:
      background-color var(--motion-fast) var(--ease-decel),
      border-color var(--motion-fast) var(--ease-decel),
      transform var(--motion-fast) var(--ease-decel),
      box-shadow var(--motion-normal) var(--ease-decel);
  }
  .card:hover {
    background: var(--surface-card-hover);
    border-color: var(--stroke-default);
    transform: translateY(-1px);
    box-shadow: var(--shadow-card);
  }
  .card.applied {
    background: var(--accent-overlay-weak);
    border-color: rgba(76,194,255,0.18);
  }
  .card.applied:hover {
    background: var(--accent-overlay);
  }
  .card.selected {
    background: var(--accent-overlay);
    border-color: rgba(76,194,255,0.45);
    box-shadow: 0 0 0 1px rgba(76,194,255,0.25);
  }
  .card.risky.applied { border-color: var(--danger-stroke); }

  .select {
    width: 18px; height: 18px;
    margin-top: 2px;
    border-radius: 4px;
    border: 1.5px solid var(--text-tertiary);
    background: transparent;
    color: var(--text-on-accent);
    display: inline-flex;
    align-items: center;
    justify-content: center;
    transition: all var(--motion-fast) var(--ease-decel);
    cursor: pointer;
    padding: 0;
  }
  .select:hover { border-color: var(--text-secondary); background: var(--surface-card-hover); }
  .card.selected .select {
    background: var(--accent-fill);
    border-color: var(--accent-fill);
  }
  .select:focus-visible { outline-offset: 1px; }

  .body { min-width: 0; }

  header {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 4px;
    flex-wrap: wrap;
  }
  h3 {
    margin: 0;
    font-size: 14px;
    font-weight: 600;
    color: var(--text-primary);
    line-height: 1.4;
    letter-spacing: -0.1px;
  }
  .desc {
    margin: 0;
    font-size: 13px;
    color: var(--text-secondary);
    line-height: 1.5;
    max-width: 72ch;
  }

  .warn {
    margin-top: 8px;
    padding: 8px 10px;
    background: var(--warning-overlay-weak);
    border: 1px solid rgba(252,225,0,0.18);
    border-radius: var(--radius-sm);
    color: #ffe680;
    font-size: 12px;
    line-height: 1.45;
    display: flex;
    align-items: flex-start;
    gap: 8px;
  }
  .warn :global(svg) { flex-shrink: 0; margin-top: 1px; }

  footer {
    display: flex;
    align-items: center;
    gap: 6px;
    margin-top: 10px;
    flex-wrap: wrap;
    font-size: 11px;
    color: var(--text-tertiary);
  }
  .ops { font-variant-numeric: tabular-nums; }
  .dot-sep { color: var(--text-disabled); }
  .preset {
    padding: 1px 7px;
    border-radius: 3px;
    background: var(--surface-card-active);
    color: var(--text-secondary);
    text-transform: capitalize;
    font-weight: 500;
    font-size: 10.5px;
    letter-spacing: 0.2px;
  }
  .applied-tag {
    display: inline-flex;
    align-items: center;
    gap: 3px;
    color: var(--success);
    font-weight: 500;
  }
  .modified-tag {
    display: inline-flex;
    align-items: center;
    gap: 4px;
    color: #ffc857;
    font-weight: 500;
  }
  .card.modified {
    border-color: rgba(255,200,87,0.32);
    background: rgba(255,200,87,0.04);
  }
  .card.modified:hover {
    background: rgba(255,200,87,0.07);
  }

  .action { padding-top: 1px; }

  @media (prefers-reduced-motion: reduce) {
    .card:hover { transform: none; }
  }
</style>

// src/lib/components/TweakCard.tsx
import './TweakCard.css';
import { useMemo } from 'react';
import { Icon } from './Icon';
import { SeverityBadge } from './SeverityBadge';
import { Toggle } from './Toggle';
import type { DetectionState, Tweak, TweakStatus } from '../../types';

type Props = {
  tweak: Tweak;
  applied: boolean;
  selected: boolean;
  status?: TweakStatus | null;
  onToggleApply: () => void;
  onToggleSelected: () => void;
};

export function TweakCard({ tweak, applied, selected, status, onToggleApply, onToggleSelected }: Props) {
  const state: DetectionState = status?.state ?? (applied ? 'applied' : 'not_applied');
  const opCount = useMemo(
    () => tweak.registry.length + tweak.services.length + tweak.appx.length + (tweak.ps_apply ? 1 : 0),
    [tweak]
  );

  const cls = [
    'tweak-card',
    applied ? 'applied' : '',
    selected ? 'selected' : '',
    state === 'modified' ? 'modified' : '',
    tweak.severity === 'risky' ? 'risky' : ''
  ].filter(Boolean).join(' ');

  return (
    <article className={cls}>
      <button
        type="button"
        className="select"
        role="checkbox"
        aria-checked={selected}
        aria-label={selected ? `Deselect ${tweak.name}` : `Select ${tweak.name}`}
        onClick={(e) => { e.stopPropagation(); onToggleSelected(); }}
      >
        {selected && <Icon name="Check" size={12} bold />}
      </button>

      <div className="body">
        <header>
          <h3>{tweak.name}</h3>
          <SeverityBadge level={tweak.severity} />
        </header>

        <p className="desc">{tweak.description}</p>

        {tweak.warning && (
          <div className="warn">
            <Icon name="AlertTriangle" size={13} />
            <span>{tweak.warning}</span>
          </div>
        )}

        <footer>
          <span className="ops" title={`${opCount} operation${opCount === 1 ? '' : 's'}`}>
            {opCount} op{opCount === 1 ? '' : 's'}
          </span>
          {tweak.presets.length > 0 && (
            <>
              <span className="dot-sep">·</span>
              {tweak.presets.map((p) => (
                <span key={p} className="preset">{p}</span>
              ))}
            </>
          )}
          {state === 'applied' ? (
            <>
              <span className="dot-sep">·</span>
              <span className="applied-tag"><Icon name="Check" size={10} bold /> Applied</span>
            </>
          ) : state === 'modified' ? (
            <>
              <span className="dot-sep">·</span>
              <span
                className="modified-tag"
                title={`${status?.ops_matching ?? 0} of ${status?.ops_total ?? 0} settings match the desired state. Another tool may have changed some of these.`}
              >
                <Icon name="AlertTriangle" size={10} />
                Modified externally ({status?.ops_matching}/{status?.ops_total})
              </span>
            </>
          ) : null}
        </footer>
      </div>

      <div className="action">
        <Toggle checked={applied} onChange={onToggleApply} />
      </div>
    </article>
  );
}
